### ISSUE TITLE
caught segfault on loading acmacs.r

### ISSUE THREAD

**Issue by davipatti** [acorg/acmacs.r#3]
I and @CaitlinWalker have been trying to install acmacs.r on her mac running os x 10.13.

Installation is fine, but then loading the library results in a caught segfault error: https://gist.github.com/CaitlinWalker/3626c6a964fa161bc46e1531827a941e

Here is the output of  `sessionInfo()` https://gist.github.com/CaitlinWalker/6c7d59ce9816e062b1b88315f0a982f2

**Comment by skepner** [comment]
Thanks David.

Could you please try the following:
1. Install Rcpp package. And then try to load acmacs.r again
2. Try to install and load acmacs.r 2.10
2. Try to install and load acmacs.r 2.9

**Comment by davipatti** [comment]
Thanks Eu, will give that a go.

**Comment by CaitlinWalker** [comment]
Thank you Eugene! Unfortunately having tried acmacs.r 2.10, then 2.9 we got the following error messages (also tried 2.3 as we thought it might be what Sam had used successfully):
2.10
https://gist.github.com/CaitlinWalker/f7c0b1dd8a81c422ed6f714234724a45
2.9
https://gist.github.com/CaitlinWalker/8379c5f643392e4d3959d67a143eeebd
2.3
https://gist.github.com/CaitlinWalker/7a3b79a379d8227338dfe20e8f65b9c3

**Comment by davipatti** [comment]
(We also tried reinstalling Rcpp, and loading acmacs.r again, but got similar errors.)

**Comment by skepner** [comment]
Thanks. There are two possibilities:
1. It does not work on 10.13. Perhaps no one tried it on 10.13 or bothered to report.
2. The problem is specific to this very computer.

Two possible variants of further processing:
1. Give me full access to that computer. I will re-build acmacs there, will have to install many packages to do it, i.e. I need to be able to do sudo. Not clear when I have time for that, unlikely I have time until 2019 (unless Derek explicitly prioritizes the task), and not clear how much time it will take. 
2. Wait for the next version of acmacs.r. I have 10.14 now and will make next version on 10.14 with ability to run it on earlier versions of macos (I hope, but not sure if it possible without wasting a lot of time), will test it on 10.12 (I don't have 10.13). I am not going to do it before March 2019 (unless Derek tells me to do it earlier).

**Comment by davipatti** [comment]
I have 10.14 and it loads acmacs.r. 

Another possibility is: @CaitlinWalker is it ok to upgrade your operating system to OS X 10.14?

**Comment by skepner** [comment]
@CaitlinWalker have you earlier upgraded macos on your computer, e.g. you had 10.12 and upgraded to 10.13? It might be the source of the problems. Then upgrading it to 10.14 would rather make things worse, imho. I would suggest formatting disk and installing 10.14 on a clean disk, and then NOT installing anything from a backup (i.e. time machine) but rather installing all the programs via downloading them from internet and changing their settings manually.

**Comment by terrycojones** [comment]
@davipatti @CaitlinWalker  You could also run whatever command you're running using `dtruss`.  I.e., just stick `dtruss` on the command line before running the command. You'll get a ton of output, all of which you can ignore. `dtruss` will show all system calls and their result. It's often very useful to see exactly what was attempted that caused a crash (or, e.g., a "File not found" error where you aren't given the file name).  Maybe the last bit of the output will be revealing. I still like the theory that some function is returning 24 and that's being passed to `munmap`. If that's the case you may be able to see where the 24 comes from. If it's not the case (I mean that a call to `munmap` is failing, you'll see something else...).

BTW, the Linux equivalent is `strace`.

**Comment by davipatti** [comment]
I have previously upgraded from 10.12 -> 10.13 -> 10.14 without doing a clean install on a formatted disk. @skepner Does that impact your advice?

---

@CaitlinWalker I think formatting your disk and installing a clean version of 10.14 is probably more effort than we want to spend getting this working on your machine, for the scope of the current project.

**Comment by skepner** [comment]
@davipatti you are lucky that upgrading did not corrupt anything important. Or Caitlin is unlucky, if she did upgrade.
I have always do clean upgrade and never advice simple upgrade, there are also other reasons besides avoiding wasting time on figuring out strange problems after upgrading.

**Comment by davipatti** [comment]
Thanks @terrycojones. @CaitlinWalker, can you copy and paste this into your terminal:

~~~bash
cd /tmp
echo "library(acmacs.R)" > load-acmacs.r
dtruss R --no-save < load-acmacs.r &> ~/dtruss.out
~~~

And then copy past the contents of `dtruss.out` to a gist. That file will be in your home directory.

**Comment by davipatti** [comment]
@skepner is it worth spending the time to test if upgrading to 10.14 fixes the issue? From my perspective it is a simple operation, and if it has a slim chance of working then it might be worth trying. But if you are sure that it is futile (I think you know more than me) then we won't bother.

I think (but please correct me if I'm wrong, @CaitlinWalker) that Caitlin has not configured her system much or at all, and therefore it is unlikely that upgrading would break (more) things.

**Comment by skepner** [comment]
Well, if Caitlin's system is corrupted due you earlier upgrade or due to something else, there is a chance that upgrading fixes the problems leading to R failure (and perhaps introduce other problems). Caitlin may experiment on her own risk, at least she will be able to install everything from scratch in the end. (I assume there is a backup of all the data that she has there.)

**Comment by terrycojones** [comment]
Or, instead of the @davipatti verboseness :-)

```sh
echo 'library(acmacs.R)' | sudo dtruss R --no-save &> ~/dtruss.out
```

Note that the `dtruss.out` file may be huge. You could just paste the output of `tail -n 200 ~/dtruss.out` to a gist.

**Comment by CaitlinWalker** [comment]
As far as I know, I didn't upgrade from 10.12 to 10.13 during this time but it is entirely possible. I also unfortunately upgraded to 10.14 during the time gap between these messages earlier, so I hope this hasn't worsened the issue. If it is only a problem for my laptop alone then it will be okay for me to carry on without being able to do this installation (ie. if this advice is no longer going to be able to be applicable to other machines)

**Comment by skepner** [comment]
I have tried dtruss on my 10.12 machine where acmacs.r was built and works:

sudo dtruss Rscript -e 'library(acmacs.r)'

The output was short (25 lines) and there is an error:
dtrace: error on enabled probe ID 2158 (ID 552: syscall::sysctl:return): invalid kernel access in action #10 at DIF offset 40

Even
sudo dtruss Rscript -e 'sessionInfo()' 
produces  no normal output and shows that error.

sudo dtruss R
dtrace: system integrity protection is on, some features will not be available
dtrace: failed to execute R: dtrace cannot control executables signed with restricted entitlements

I think to run dtruss with R one has to disable system integrity protection (by rebooting into system restore mode or whatever it is called and disabling in that mode).

**Comment by skepner** [comment]
@CaitlinWalker Have you tried to load acmacs.r upon upgrading to 10.14?

**Comment by davipatti** [comment]
We reinstalled r, acmacs.r and it's dependencies, and it now works.

**Comment by davipatti** [comment]
This issue has popped up again. I have tried reinstalling everything from scratch. Please see the session details below:

~~~
david@puck~> R

R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Pop!_OS 19.04

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.3.5.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1
> library("Rcpp")
> library("acmacs.r")

 *** caught segfault ***
address 0x4c, cause 'memory not mapped'

Traceback:
 1: .External(list(name = "InternalFunction_invoke", address = <pointer: 0x56095570d8d0>,     dll = list(name = "Rcpp", path = "/usr/local/lib/R/site-library/Rcpp/libs/Rcpp.so",         dynamicLookup = TRUE, handle = <pointer: 0x5609566101e0>,         info = <pointer: 0x560954272cc0>), numParameters = -1L),     <pointer: 0x5609556fca60>)
 2: acmacs.__init()
 3: fun(libname, pkgname)
 4: doTryCatch(return(expr), name, parentenv, handler)
 5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 6: tryCatchList(expr, classes, parentenv, handlers)
 7: tryCatch(fun(libname, pkgname), error = identity)
 8: runHook(".onAttach", ns, dirname(nspath), nsname)
 9: attachNamespace(ns, pos = pos, deps, exclude, include.only)
10: doTryCatch(return(expr), name, parentenv, handler)
11: tryCatchOne(expr, names, parentenv, handlers[[1L]])
12: tryCatchList(expr, classes, parentenv, handlers)
13: tryCatch({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)}, error = function(e) {    P <- if (!is.null(cc <- conditionCall(e)))         paste(" in", deparse(cc)[1L])    else ""    msg <- gettextf("package or namespace load failed for %s%s:\n %s",         sQuote(package), P, conditionMessage(e))    if (logical.return)         message(paste("Error:", msg), domain = NA)    else stop(msg, call. = FALSE, domain = NA)})
14: library("acmacs.r")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 1
R is aborting now ...
fish: “R” terminated by signal SIGSEGV (Address boundary error)
david@puck~> ls /usr/local/lib/R/site-library/Rcpp/libs/Rcpp.so
/usr/local/lib/R/site-library/Rcpp/libs/Rcpp.so*
~~~

**Comment by davipatti** [comment]
The acmacs.r readme says to use R3.6. Is there a specific version of R 3.6 I should be using/

**Comment by skepner** [comment]
David, could you please remove acmacs.r package and install one from
acorg:/syn/eu/R/acmacs.r_3.6_R_x86_64-pc-linux-gnu.tar.gz
Please let me know if it works.

**Comment by davipatti** [comment]
No, same error:

https://gist.github.com/davipatti/0a2481bbcaadc3daf0ee78be17fbb386

**Comment by skepner** [comment]
It's crashed while loading Rcpp.so. What version of Rcpp is installed?

**Comment by davipatti** [comment]
1.0.1

**Comment by skepner** [comment]
I can only suggest building acmacs on your machine. You may do it yourself,
or give me ssh access with sudo for installing packages. Let's discuss in
email.
