### ISSUE TITLE
Setting of projection transformation matrix not allowed

### ISSUE THREAD

**Issue by shwilks** [acorg/acmacs.r#4]
Although documented in the help files, the code below:

```r
chart <- new(acmacs.r::acmacs.Chart, path_to_acd1)
chart$projections[[1]]$transformation <- matrix(c(1, 0, 0, 1), nrow=2, byrow=TRUE)
```

Returns the error:

```
Error in (new("activeBindingFunction", .Data = function (x)  : 
  property is read only
```

**Comment by skepner** [comment]
It is not going to work, I guess it is a bug or misfeature of Rcpp (or R).

Does not work:
`chart$projections[[1]]$transformation <- matrix()`

Works:
`prj <- chart$projections[[1]]; prj$transformation <- matrix()`

I have no idea why. 

There is set_transformation method in v3.0, i.e.
`chart$projections[[1]]$set_transformation(matrix(...))`
