### ISSUE TITLE
acmacs.r 4.5  -  unable to load shared object '[...]/acmacs.r.so': libacmacswhoccdata.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by CarlijnB** [acorg/acmacs.r#8]
Hi,

I have R 3.6 and am trying to load acmacs.r version 4.5 on Linux (to work with Racmacs), but am constantly faced with this error message:

>library(acmacs.r)
Error: package or namespace load failed for ‘acmacs.r’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/vetschool/R/x86_64-pc-linux-gnu-library/3.6/acmacs.r/libs/acmacs.r.so':
  libacmacswhoccdata.so.1: cannot open shared object file: No such file or directory

I have Rcpp 1.0.5, devtools, roxygen2, testthat installed.

Please can you advise? (duplicate posted on Racmacs page)

Thank you.

Carlijn

**Comment by skepner** [comment]
Hi Carlijn,
It seems I forgot to include libacmacswhoccdata.so.1 in that release, sorry.
The only solution for you is to upgrade R and use acmacs.r 5. There should be v5.1 in a couple of days, 5.0 is buggy.
Eugene

**Comment by CarlijnB** [comment]
Thank you very much Eugene. I'm just upgrading R and will be looking out for v5.1!

**Comment by skepner** [comment]
Hi Carlijn,
I have made v5.1 of acmacs.r, please use it.
https://github.com/acorg/acmacs.r/releases/tag/v5.1
Eugene

**Comment by CarlijnB** [comment]
many thanks Eugene! I can confirm I no longer get this error message. (although I had to upgrade both my Ubuntu OS and R to get acmacs.r v5.1 to work, because of some system dependencies)
